---
name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: fish {0}

    steps:
      - uses: actions/checkout@v2

      - uses: fish-actions/install-fish@v1

      - name: Install Scuba
        run: |
          source $GITHUB_WORKSPACE/functions/_scuba_sub_install.fish
          _scuba_sub_install $GITHUB_WORKSPACE

      - run: scuba --version

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actionsx/prettier@v2
        with:
          args: --check .

  super-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MD: true
          VALIDATE_YAML: true
